import React from "react";
import styled from "styled-components";

import { PostType } from "@/types";
import testImg from "@assets/images/test.jpg";

interface Props {
    post: PostType;
}

const PostContent = ({ post }: Props) => {
    return (
        <TestPost>
            <div className="post__content">{post.content}</div>
            <div className="container__images">
                {post.image.length > 0 && (
                    <>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>{" "}
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/29/12/29/pumpkin-8349988_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/10/22/20/11/flowers-8334774_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/12/07/10/59/giraffe-8435321_1280.jpg"
                            }
                            alt=""
                        ></img>
                        <img
                            src={
                                "https://cdn.pixabay.com/photo/2023/11/24/16/10/leaves-8410237_1280.jpg"
                            }
                            alt=""
                        ></img>
                    </>
                )}
            </div>
        </TestPost>
    );
};

const TestPost = styled.div`
    background-color: #ffffff;
    margin: 25px 0 10px 0;
    border-radius: 5px;

    .post__content {
        height: 100px;
    }

    img {
        height: 300px;
    }

    .container__images {
        display: flex;
        z-index: 3;
    }
`;

export default PostContent;
